RED=\033[0;31m
NC=\033[0m

webpack:
	./node_modules/.bin/webpack --config=tpl/build/saas/entrance.webpack.config.js --bail && \
	./node_modules/.bin/webpack --config=tpl/build/saas/gaokao.webpack.config.js --bail
